### ISSUE TITLE
Diagonal mask in Laplacian computation

### ISSUE THREAD

**Issue by asiraudin** [qym7/SparseDiff#2]
Hi,

Congrats for this nice work and thanks for sharing your code.

I'm a bit confused with something you do in the computation of the of the Laplacian : 

```      
L = self.compute_laplacian(A, normalize=False)
mask_diag = 2 * L.shape[-1] * torch.eye(A.shape[-1]).type_as(L).unsqueeze(0)
mask_diag = mask_diag * (~mask.unsqueeze(1)) * (~mask.unsqueeze(2))
L = L * mask.unsqueeze(1) * mask.unsqueeze(2) + mask_diag
```

Could you explain me why you add this mask to the diagonal of the Laplacian ?

Best,
Antoine

**Comment by qym7** [comment]
Hi Antoine,

Thanks for proposing this question!

The diag_mask helps calculate the number of components in a graph.

For example, if the maximum number of nodes is 9 but our connected graph with a single component only has 8 nodes, we adjust the 9th dimension to 18, which is like the highest eigenvalue a graph of 9 nodes could have. 

This ensures that the number of components given by sum(eigenvalues<1e-4) will be 1, otherwise, this 9th dimension with 0 values will introduce another 0 eigenvalue and lead to 2 components inside the graph with 8 nodes.

Best,
